# Permalinks
permalink:           pretty

# Setup
title:               A Worm's Wormhole
tagline:             A boom pow standard man
url:                 http://tomasedasonno2.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tommy Zhang
  url:               
  email:             tommyzhang@uchicago.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tomasedasonno2

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
